# Generated by Django 5.2.7 on 2025-10-28 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('read_time', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
