# Generated by Django 5.2.7 on 2025-10-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
